# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(724, 402)
        MainWindow.setMinimumSize(QtCore.QSize(724, 402))
        MainWindow.setMaximumSize(QtCore.QSize(724, 402))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pandastablewidget = DataTableWidget(self.centralwidget)
        self.pandastablewidget.setGeometry(QtCore.QRect(0, 110, 363, 251))
        self.pandastablewidget.setMinimumSize(QtCore.QSize(363, 251))
        self.pandastablewidget.setMaximumSize(QtCore.QSize(363, 251))
        self.pandastablewidget.setObjectName("pandastablewidget")
        self.pushButton_queding1 = QtWidgets.QPushButton(self.pandastablewidget)
        self.pushButton_queding1.setGeometry(QtCore.QRect(200, 10, 56, 21))
        self.pushButton_queding1.setObjectName("pushButton_queding1")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 100, 371, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(360, 0, 20, 391))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 247, 78))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_logdatabase = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_logdatabase.setObjectName("pushButton_logdatabase")
        self.horizontalLayout.addWidget(self.pushButton_logdatabase)
        self.pushButton_opendatabase = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_opendatabase.setObjectName("pushButton_opendatabase")
        self.horizontalLayout.addWidget(self.pushButton_opendatabase)
        self.pushButton_openfile = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_openfile.setObjectName("pushButton_openfile")
        self.horizontalLayout.addWidget(self.pushButton_openfile)
        self.pushButton_sqllanguage = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_sqllanguage.setObjectName("pushButton_sqllanguage")
        self.horizontalLayout.addWidget(self.pushButton_sqllanguage)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_save = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_2.addWidget(self.pushButton_save)
        self.pushButton_datareturn = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_datareturn.setObjectName("pushButton_datareturn")
        self.horizontalLayout_2.addWidget(self.pushButton_datareturn)
        self.pushButton_cleardata = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_cleardata.setObjectName("pushButton_cleardata")
        self.horizontalLayout_2.addWidget(self.pushButton_cleardata)
        self.pushButton_view = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_view.setObjectName("pushButton_view")
        self.horizontalLayout_2.addWidget(self.pushButton_view)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_Minmax = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_Minmax.setCheckable(True)
        self.radioButton_Minmax.setChecked(False)
        self.radioButton_Minmax.setObjectName("radioButton_Minmax")
        self.horizontalLayout_3.addWidget(self.radioButton_Minmax)
        self.radioButton_Zscore = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_Zscore.setObjectName("radioButton_Zscore")
        self.horizontalLayout_3.addWidget(self.radioButton_Zscore)
        self.radioButton_xiaoshudingbiao = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_xiaoshudingbiao.setObjectName("radioButton_xiaoshudingbiao")
        self.horizontalLayout_3.addWidget(self.radioButton_xiaoshudingbiao)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.comboBox_attributes = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_attributes.setGeometry(QtCore.QRect(420, 0, 60, 19))
        self.comboBox_attributes.setObjectName("comboBox_attributes")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 0, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_comboboxattributes = QtWidgets.QLabel(self.centralwidget)
        self.label_comboboxattributes.setGeometry(QtCore.QRect(490, 0, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_comboboxattributes.setFont(font)
        self.label_comboboxattributes.setObjectName("label_comboboxattributes")
        self.qtpandas_attributewidget = DataTableWidget(self.centralwidget)
        self.qtpandas_attributewidget.setGeometry(QtCore.QRect(410, 20, 270, 133))
        self.qtpandas_attributewidget.setMinimumSize(QtCore.QSize(270, 133))
        self.qtpandas_attributewidget.setMaximumSize(QtCore.QSize(270, 133))
        self.qtpandas_attributewidget.setObjectName("qtpandas_attributewidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(370, 160, 351, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_pciture = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_pciture.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_pciture.setObjectName("gridLayout_pciture")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 724, 18))
        self.menubar.setObjectName("menubar")
        self.menuPreprocess = QtWidgets.QMenu(self.menubar)
        self.menuPreprocess.setObjectName("menuPreprocess")
        self.menuClassify = QtWidgets.QMenu(self.menubar)
        self.menuClassify.setObjectName("menuClassify")
        self.menuCluster = QtWidgets.QMenu(self.menubar)
        self.menuCluster.setObjectName("menuCluster")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuPreprocess.menuAction())
        self.menubar.addAction(self.menuClassify.menuAction())
        self.menubar.addAction(self.menuCluster.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_queding1.setText(_translate("MainWindow", "确定"))
        self.pushButton_logdatabase.setText(_translate("MainWindow", "登录数据库"))
        self.pushButton_opendatabase.setText(_translate("MainWindow", "打开数据库"))
        self.pushButton_openfile.setText(_translate("MainWindow", "打开其他文件"))
        self.pushButton_sqllanguage.setText(_translate("MainWindow", "SQL语言"))
        self.pushButton_save.setText(_translate("MainWindow", "保存"))
        self.pushButton_datareturn.setText(_translate("MainWindow", "数据还原"))
        self.pushButton_cleardata.setText(_translate("MainWindow", "数据清空"))
        self.pushButton_view.setText(_translate("MainWindow", "视图"))
        self.label.setText(_translate("MainWindow", "数据归一化"))
        self.radioButton_Minmax.setText(_translate("MainWindow", "最小-最大规范化"))
        self.radioButton_Zscore.setText(_translate("MainWindow", "z分数规范化"))
        self.radioButton_xiaoshudingbiao.setText(_translate("MainWindow", "小数定标规范化"))
        self.label_2.setText(_translate("MainWindow", "选择属性"))
        self.label_comboboxattributes.setText(_translate("MainWindow", "属性值"))
        self.menuPreprocess.setTitle(_translate("MainWindow", "数据预处理"))
        self.menuClassify.setTitle(_translate("MainWindow", "分类"))
        self.menuCluster.setTitle(_translate("MainWindow", "聚类"))

from qtpandas.views.DataTableView import DataTableWidget
